export const stories = [
  {
    value: [
      'There once was a young ',
      ' from ',
      '. They had ',
      ' siblings that all share the same ',
      '. One day, ',
      ', the oldest sibling decided they had had enough and bought a new ',
      ' to use for transportation. This new mode of transportation was so ',
      ' that all of the other siblings felt ',
      '. They had enough and now they all ',
      ' to get around.',
    ],
    title: 'Sibling Rivalry',
    blanks: [
      'animal',
      'place',
      'number',
      'mode of transportation',
      'name',
      'animal',
      'adjective',
      'feeling',
      'movement',
    ],
  },
  {
    value: [
      '',
      ' was a ',
      ' by day, but a ',
      ' by night. Nobody knew of the double life they were leading until they went to ',
      ' and ran into ',
      '. After being offered the part of a ',
      ' in the next major motion picture titled ',
      ', they declined so that their secret identity would not be revealed. Hollywood was ',
      ', but heading home to their ',
      ', ',
      ', felt great.',
    ],
    title: 'Double Life',
    blanks: [
      'name',
      'occupation',
      'occupation',
      'place',
      'actor or actress',
      'occupation',
      'made up movie name',
      'feeling',
      'pet',
      'name',
    ],
  },
  {
    value: [
      'There was an old man that lived in ',
      '. He did not like to go outside because he was afraid of the ',
      '. One day he really needed a(n) ',
      ', so he braved the walk to the ',
      '. On his way he encountered a ',
      ', and was very ',
      '. He decided the best way to handle the situation was to name it ',
      '. They quickly became best buds and spend every day ',
      '. The End.',
    ],
    title: 'Overcoming Fear',
    blanks: [
      'place',
      'animals',
      'grocery item',
      'place',
      'animal from above',
      'feeling',
      'name',
      'activity',
    ],
  },
]
